import { Geist, Geist_Mono, Baloo_Da_2 } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const balooda = Baloo_Da_2({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], // You can pick the weights you need
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${balooda.className} antialiased max-w-3xl mx-auto mb-16 px-4 sm:px-6 lg:px-8`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
